name: Dependency Update PR

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install -g npm-check-updates

      - name: Update dependencies
        run: ncu -u && npm install

      - name: Check for changes
        run: |
          if git diff --quiet; then
            echo "No updates found."
            exit 0
          fi

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b dependency-updates
          git add package.json package-lock.json
          git commit -m "chore: update dependencies"

      - name: Push changes
        run: git push -u origin dependency-updates --force

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dependency-updates
          base: main
          title: "chore: update dependencies"
          body: "Automated dependency updates"
          labels: "dependencies"
          draft: false
